CREATE DATABASE Customer_churn_business;
USE Customer_churn_business;

SELECT * FROM customer_churn;

Alter TABLE Customer_churn
ADD COLUMN churned_status VARCHAR(10); 

UPDATE Customer_churn
SET churned_status=case
WHEN churn=1 THEN "Yes"
WHEN churn=0 THEN "No"
end;

-- 1.How many total customers are present in the dataset?
 SELECT count(*) from customer_churn;

 -- 2.How many customers have churned and how many are retained?
SELECT churned_status,count(*) as total from customer_churn
group by churned_status;

-- 3.What are the distinct countries represented in the dataset?
SELECT distinct country  as distinct_countries from customer_churn;

-- 4.How many customers belong to each signup channel?
SELECT signup_channel,count(*) No_of_customers FROM customer_churn
GROUP BY signup_channel;

-- 5.How many records contain missing CSAT scores?
Select count(*) as No_of_missing_csat_score FROM customer_churn where csat_score IS NULL;

-- 6.What is the gender distribution of customers?
SELECT gender,count(gender) FROM customer_churn GROUP BY gender;

-- 7.What is the average age of churned vs non-churned customers?
SELECT churned_status,avg(age) as avg_age FROM customer_churn GROUP BY churned_status;

-- 8.What is the total revenue generated by all customers?
SELECT SUM(total_revenue) as total_revenue FROM customer_churn; 

-- 9.What is the average monthly fee for each contract type?
SELECT contract_type,avg(monthly_fee) as avg_monthly_fee FROM customer_churn
GROUP BY contract_type;

-- 10.What is the average number of monthly logins by churn status?
SELECT churned_status,avg(monthly_logins) as avg_monthly_login FROM customer_churn
GROUP BY churned_status;

-- 11.Which payment method is most commonly used by customers?
SELECT payment_method, count(*) AS Total_customers FROM customer_churn
GROUP BY payment_method
ORDER BY count(*) LIMIT 1;

-- 12.What is the average tenure (in months) of customers?
SELECT ROUND(avg(tenure_months),2) AS Avg_tenure_in_months FROM customer_churn;

-- 13.What is the churn rate for each contract type?
SELECT contract_type,count(*) AS total_customers,
sum(case when churn=1 then 1 ELSE 0 END)as churned_customers,
round(sum(case when churn=1 then 1 ELSE 0 END)*100 / count(*) ,2) AS churn_rate
FROM customer_churn 
GROUP BY contract_type;

-- 14.How does average tenure differ between churned and retained customers?
SELECT churned_status,avg(tenure_months) AS average_tenure  FROM customer_churn
GROUP BY churned_status;

-- 15.What is the relationship between CSAT score and churn?
SELECT csat_score,count(*) as total_customers,
sum(CASE WHEN churn=1 THEN 1 ELSE 0 END) as churned_customer,
Round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100 / count(*),2) as churn_rate
FROM customer_churn
GROUP BY csat_score;

-- 16.Do customers with more support tickets churn more frequently?
SELECT support_tickets,
       COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate
FROM customer_churn
GROUP BY support_tickets
ORDER BY support_tickets;

-- 17.What is the churn rate by complaint type?
SELECT complaint_type,
round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100 / count(*),2) as churn_rate
FROM customer_churn
GROUP BY complaint_type;


-- 18.Does a recent price increase impact customer churn?
SELECT price_increase_last_3m,count(*) as total_customer,
sum(CASE WHEN churn=1 THEN 1 ELSE 0 END) AS churned_customers,
sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100 / count(*) AS churned_rate
FROM customer_churn
GROUP BY price_increase_last_3m;

-- 19.Which signup channel has the highest churn rate?
SELECT signup_channel,count(*) as total_customers,sum(CASE WHEN churn=1 THEN 1 ELSE 0 END) AS churned_customers,
round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100/count(*),2) AS churned_rate
FROM customer_churn
GROUP BY signup_channel
ORDER BY churned_rate DESC LIMIT 1;


-- 20.How does last login activity differ for churned vs retained customers?
SELECT
  CASE
    WHEN last_login_days_ago <= 7 THEN '0–7 days'
    WHEN last_login_days_ago <= 30 THEN '8–30 days'
    ELSE '31+ days'
  END AS login_bucket,
  COUNT(*) AS total_customers,
  SUM(CASE WHEN churn=1 THEN 1 ELSE 0 END) AS churned_customers,
  ROUND(SUM(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100.0 / COUNT(*),2) AS churn_rate
FROM customer_churn
GROUP BY login_bucket;


-- 🔹 Predictive (Logic-Based) Questions
-- 21.How many customers are at potential churn risk (low CSAT & high support tickets)?
SELECT COUNT(*) AS risk_customers
FROM customer_churn
WHERE csat_score <= 2
AND churn = 0;


-- 22.Which customers have been inactive for more than 30 days?
SELECT customer_id,last_login_days_ago FROM customer_churn WHERE last_login_days_ago>30 
ORDER BY last_login_days_ago DESC ; 
select tenure_months from customer_churn;

-- 23.Are customers with shorter tenure more likely to churn?
SELECT CASE 
WHEN tenure_months<6 then "shorter tenure(<6 months)"
ELSE "Longer Tenure(>= 6 months)"
END AS tenure_group,
count(*) AS total_customers,
sum(CASE WHEN churn=1 THEN 1 ELSE 0 END) AS churned_customers,
round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100/count(*),2) AS churned_rate
FROM customer_churn
GROUP BY tenure_group;

-- 24.Does lower usage (monthly logins) indicate higher churn probability?
SELECT CASE WHEN
monthly_logins<5 then "lower logins (<5)"
ELSE "higher logins (>=5)"
END AS logingroup,
count(*) AS total_customers,
sum(CASE WHEN churn=1 THEN 1 ELSE 0 END) AS churned_customers,
round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100/count(*),2) AS churned_rate
FROM customer_churn
GROUP BY logingroup ;

-- 25.Which customers generate high revenue but still churn?
SELECT customer_id,total_revenue FROM customer_churn where churn=1
AND total_revenue>(select avg(total_revenue) FROM customer_churn)
ORDER BY total_revenue;

-- 🔹 Prescriptive Analysis Questions
-- 26.Which retained customers should be targeted for retention offers?
SELECT customer_id,total_revenue,tenure_months,monthly_logins,csat_score,support_tickets
FROM customer_churn
WHERE churn=0
AND (
tenure_months<6
OR monthly_logins<5
OR csat_score<3
OR support_tickets>3)
ORDER BY total_revenue DESC LIMIT 20;

-- 27.Which customers are ideal for referral or loyalty programs?
SELECT customer_id,marketing_click_rate,referral_count,csat_score 
FROM customer_churn
WHERE CHURN=0
AND csat_score>=4
ORDER BY referral_count DESC ,marketing_click_rate DESC 
LIMIT 10;

-- 28.Which customer segment should receive discounted pricing plans?
SELECT customer_segment,
       COUNT(*) AS total_customers,
       AVG(csat_score) AS avg_csat,
       SUM(CASE WHEN churn=1 THEN 1 ELSE 0 END) AS churned_customers,
      round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100/count(*),2) AS churned_rate 
FROM customer_churn
GROUP BY customer_segment
ORDER BY churned_customers DESC, avg_csat ASC;

-- 29.What customer group needs service quality improvement the most?
SELECT customer_segment,
       COUNT(*) AS total_customers,
       avg(support_tickets) AS avg_support_tickets,
       round(sum(CASE WHEN support_tickets>0 THEN 1 ELSE 0 END)*100/count(*),2) AS support_ticket_rate
       FROM customer_churn
       GROUP BY customer_segment
       ORDER BY avg_support_tickets DESC;
       

-- 30.Which contract type should the company promote to reduce churn?
SELECT contract_type,count(*) as total_customer,
SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) AS churned_customers,
round(sum(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100/count(*),2) AS churned_rate 
FROM customer_churn
GROUP BY contract_type;

-- 🔹 Advanced Queries ⭐

-- 31.Rank countries based on churn rate.
SELECT 
    country,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate,
    RANK() OVER (
        ORDER BY SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) * 1.0 / COUNT(*) DESC
    ) AS churn_rank
FROM customer_churn
GROUP BY country;

-- 32.Segment customers into New, Growing, and Loyal based on tenure.
SELECT customer_id,
CASE
WHEN tenure_months<6 THEN 'New'
WHEN tenure_months BETWEEN 6 AND 24 THEN 'growing'
ELSE 'loyal'
END AS customer_segment
FROM customer_churn;

-- 33.Find the top 5 customers with the highest lifetime revenue.
SELECT customer_id,total_revenue
FROM customer_churn
ORDER BY total_revenue
DESC LIMIT 5;

-- 34.Identify the customer segment with the highest churn risk.
SELECT customer_segment,
ROUND(SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate
FROM customer_churn
GROUP BY customer_segment
ORDER BY churn_rate
DESC LIMIT 1;

-- 35.Compare churn rates between high-value and low-value customers.
SELECT 
CASE
WHEN total_revenue>(select avg(total_revenue) from customer_churn) THEN 'high_value_customer'
Else 'low_value_customer'
END AS customer_revenue_category,
ROUND(SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate
FROM customer_churn
GROUP BY customer_revenue_category;

-- 36.Which combination of contract type and payment method has the lowest churn?
SELECT contract_type, payment_method,
ROUND(SUM(CASE WHEN churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate
FROM customer_churn 
GROUP BY contract_type, payment_method
ORDER BY churn_rate ASC
LIMIT 1;

-- 37.What factors most commonly appear among churned customers?
SELECT  csat_score, count(*) as churned_customer,
ROUND(SUM(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS churn_rate
FROM customer_churn
GROUP BY csat_score

UNION ALL

SELECT  complaint_type, count(*) as churned_customer,
ROUND(SUM(CASE WHEN churn=1 THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS churn_rate
FROM customer_churn
GROUP BY complaint_type;

-- 38.Create a churn risk category (High / Medium / Low) using multiple conditions.
SELECT *,
CASE WHEN csat_score<2 OR support_tickets>5  OR last_login_days_ago>30 THEN 'high_risk'
     WHEN csat_score>=2 AND support_tickets BETWEEN 3 AND 5 THEN 'medium_risk'
     ELSE 'low_risk'
END AS 'risk_category'
FROM customer_churn;

-- 39.Identify customers whose behavior changed after a price increase.
SELECT * FROM customer_churn WHERE price_increase_last_3m='yes'
AND(
monthly_logins<5 
OR usage_growth_rate<0
OR last_login_days_ago>30
);

-- 40.Which business metric should management prioritize to reduce churn?
SELECT 'csat_score' AS metric,
ROUND(AVG(CASE WHEN churn=1 THEN csat_score END),2) AS churned_avg,
ROUND(AVG(CASE WHEN churn=0 THEN csat_score END),2) AS retained_avg
FROM customer_churn

UNION ALL

SELECT 'support_tickets',
ROUND(AVG(CASE WHEN churn=1 THEN support_tickets END),2),
ROUND(AVG(CASE WHEN churn=0 THEN support_tickets END),2)
FROM customer_churn

UNION ALL

SELECT 'last_login_days_ago',
ROUND(AVG(CASE WHEN churn=1 THEN last_login_days_ago END),2),
ROUND(AVG(CASE WHEN churn=0 THEN last_login_days_ago END),2)
FROM customer_churn;
